### ISSUE TITLE
floyd/main.py type error.

### ISSUE THREAD

**Issue by DonaldDai** [floydhub/floyd-cli#179]
```text
Traceback (most recent call last):
  File "/Users/zhilian/anaconda2/bin/floyd", line 11, in <module>
    sys.exit(cli())
  File "/Users/zhilian/anaconda2/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/zhilian/anaconda2/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/zhilian/anaconda2/lib/python2.7/site-packages/click/core.py", line 1063, in invoke
    Command.invoke(self, ctx)
  File "/Users/zhilian/anaconda2/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/zhilian/anaconda2/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/zhilian/anaconda2/lib/python2.7/site-packages/floyd/main.py", line 33, in cli
    check_cli_version()
  File "/Users/zhilian/anaconda2/lib/python2.7/site-packages/floyd/main.py", line 62, in check_cli_version
    msg_parts.apend("    conda install -y -c conda-forge -c floydhub floyd-cli")
AttributeError: 'list' object has no attribute 'apend'
Sentry is attempting to send 1 pending error messages
Waiting up to 10 seconds
Press Ctrl-C to quit
```

The 'apend' should be 'append'.

**Comment by houqp** [comment]
Thanks for the report, this should have been fixed in the latest version. Which version are you using? Could you try updating the cli?

**Comment by DonaldDai** [comment]
It's the latest version...the error still happen after I updated floyd-cli.

**Comment by znagler** [comment]
I'm having the same issue.  It happens when I try `floyd init foo` or `floyd upgrade`

**Comment by DonaldDai** [comment]
@znagler Just replace the 'apend' with 'append' can fix it.

**Comment by jalammar** [comment]
@DonaldDai's suggestion worked for me. Thank you!

Edit 'floyd/main.py' to change the one "apend" to "append". The error message should give you its full path.

**Comment by jalammar** [comment]
@houqp I was running an old version (`0.10.33`). Upgraded to `0.10.37` now and it works fine.

**Comment by DonaldDai** [comment]
@houqp The problem really happened in `0.10.36` and it fixed in `0.10.37`.
